name = "youtube-summarizer"
main = "src/worker.js"
compatibility_date = "2024-03-12"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "youtube-summarizer"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[vars]
YOUTUBE_CHANNEL_ID = ""
YOUTUBE_API_KEY = ""
DIFY_API_KEY = ""