name = "youtube-summarizer"
main = "src/worker.js"
compatibility_date = "2024-03-12"

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "youtube-summarizer"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[vars]
YOUTUBE_CHANNEL_ID = "" # @WRITE_HERE
YOUTUBE_API_KEY = "" # @WRITE_HERE
DIFY_API_KEY = "" # @WRITE_HERE